// Typed wrappers around Wails-generated Go bindings
// @ts-ignore — generated by wails at build time
import { GetConnectionStatus, GetApps, HideApp, ShowApp, InstallAPK, RunSetup, IsDeviceOwnerInstalled, OpenFileDialog } from '../../wailsjs/go/main/App'
// @ts-ignore
import { EventsOn } from '../../wailsjs/runtime/runtime'

export interface App {
  package: string
  label: string
  icon: string
  hidden: boolean
}

export interface ConnectionStatus {
  connected: boolean
  serial: string
}

export const getConnectionStatus = (): Promise<ConnectionStatus> => GetConnectionStatus()
export const getApps = (): Promise<App[]> => GetApps()
export const hideApp = (pkg: string): Promise<void> => HideApp(pkg)
export const showApp = (pkg: string): Promise<void> => ShowApp(pkg)
export const installAPK = (path: string): Promise<void> => InstallAPK(path)
export const openFileDialog = (): Promise<string> => OpenFileDialog()
export const runSetup = (): Promise<void> => RunSetup()
export const isDeviceOwnerInstalled = (): Promise<boolean> => IsDeviceOwnerInstalled()
export const onConnectionChange = (cb: (status: ConnectionStatus) => void) => {
  EventsOn('connection:change', cb)
}
