// Typed wrappers around Wails-generated Go bindings
// @ts-ignore — generated by wails at build time
import { GetConnectionStatus, GetApps, HideApp, ShowApp, InstallAPK, RunSetup, IsDeviceOwnerInstalled, OpenFileDialog, UpdateAdmin, UninstallApp, GetKnownStores } from '../../wailsjs/go/main/App'
// @ts-ignore
import { EventsOn } from '../../wailsjs/runtime/runtime'

export interface App {
  package: string
  label: string
  icon: string
  hidden: boolean
}

export interface ConnectionStatus {
  connected: boolean
  serial: string
}

export const getConnectionStatus = (): Promise<ConnectionStatus> => GetConnectionStatus()
export const getApps = (): Promise<App[]> => GetApps()
export const hideApp = (pkg: string): Promise<void> => HideApp(pkg)
export const showApp = (pkg: string): Promise<void> => ShowApp(pkg)
export const installAPK = (path: string): Promise<void> => InstallAPK(path)
export const openFileDialog = (): Promise<string> => OpenFileDialog()
export const runSetup = (): Promise<void> => RunSetup()
export const isDeviceOwnerInstalled = (): Promise<boolean> => IsDeviceOwnerInstalled()
export const onConnectionChange = (cb: (status: ConnectionStatus) => void) => {
  EventsOn('connection:change', cb)
}

export const updateAdmin = (): Promise<void> => UpdateAdmin()
export const onAdminVersionMismatch = (cb: (info: { installedVersion: number, bundledVersion: number }) => void) => {
  EventsOn('admin:version-mismatch', cb)
}

export const uninstallApp = (pkg: string): Promise<void> => UninstallApp(pkg)
export const getKnownStores = (): Promise<string[]> => GetKnownStores()
