// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {adb} from '../models';

export function ExportContactsToDesktop():Promise<string>;

export function GetApps():Promise<Array<adb.App>>;

export function GetConnectionStatus():Promise<Record<string, any>>;

export function GetContactsBackupInfo():Promise<Record<string, any>>;

export function GetGoogleAccountCount():Promise<number>;

export function GetKnownStores():Promise<Array<string>>;

export function HideApp(arg1:string):Promise<void>;

export function ImportContactsFromBackup():Promise<void>;

export function InstallAPK(arg1:string):Promise<void>;

export function IsDeviceOwnerInstalled():Promise<boolean>;

export function OpenAccountSettings():Promise<void>;

export function OpenFileDialog():Promise<string>;

export function RunInstall():Promise<void>;

export function RunReset():Promise<void>;

export function ShowApp(arg1:string):Promise<void>;

export function UninstallApp(arg1:string):Promise<void>;

export function UpdateAdmin():Promise<void>;
