// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ExportContactsToDesktop() {
  return window['go']['main']['App']['ExportContactsToDesktop']();
}

export function GetApps() {
  return window['go']['main']['App']['GetApps']();
}

export function GetConnectionStatus() {
  return window['go']['main']['App']['GetConnectionStatus']();
}

export function GetContactsBackupInfo() {
  return window['go']['main']['App']['GetContactsBackupInfo']();
}

export function GetGoogleAccountCount() {
  return window['go']['main']['App']['GetGoogleAccountCount']();
}

export function GetKnownStores() {
  return window['go']['main']['App']['GetKnownStores']();
}

export function HideApp(arg1) {
  return window['go']['main']['App']['HideApp'](arg1);
}

export function ImportContactsFromBackup() {
  return window['go']['main']['App']['ImportContactsFromBackup']();
}

export function InstallAPK(arg1) {
  return window['go']['main']['App']['InstallAPK'](arg1);
}

export function IsDeviceOwnerInstalled() {
  return window['go']['main']['App']['IsDeviceOwnerInstalled']();
}

export function OpenAccountSettings() {
  return window['go']['main']['App']['OpenAccountSettings']();
}

export function OpenFileDialog() {
  return window['go']['main']['App']['OpenFileDialog']();
}

export function RunInstall() {
  return window['go']['main']['App']['RunInstall']();
}

export function RunReset() {
  return window['go']['main']['App']['RunReset']();
}

export function ShowApp(arg1) {
  return window['go']['main']['App']['ShowApp'](arg1);
}

export function UninstallApp(arg1) {
  return window['go']['main']['App']['UninstallApp'](arg1);
}

export function UpdateAdmin() {
  return window['go']['main']['App']['UpdateAdmin']();
}
