// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {adb} from '../models';

export function GetApps():Promise<Array<adb.App>>;

export function GetConnectionStatus():Promise<Record<string, any>>;

export function HideApp(arg1:string):Promise<void>;

export function InstallAPK(arg1:string):Promise<void>;

export function IsDeviceOwnerInstalled():Promise<boolean>;

export function OpenFileDialog():Promise<string>;

export function RunSetup():Promise<void>;

export function ShowApp(arg1:string):Promise<void>;
