// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetConnectionStatus() {
    return window['go']['main']['App']['GetConnectionStatus']();
}

export function IsDeviceOwnerInstalled() {
    return window['go']['main']['App']['IsDeviceOwnerInstalled']();
}

export function GetApps() {
    return window['go']['main']['App']['GetApps']();
}

export function HideApp(arg1) {
    return window['go']['main']['App']['HideApp'](arg1);
}

export function ShowApp(arg1) {
    return window['go']['main']['App']['ShowApp'](arg1);
}

export function InstallAPK(arg1) {
    return window['go']['main']['App']['InstallAPK'](arg1);
}

export function RunSetup() {
    return window['go']['main']['App']['RunSetup']();
}
