// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface ConnectionStatus {
    connected: boolean;
    serial: string;
}

export interface AppInfo {
    package: string;
    label: string;
    icon: string;
    hidden: boolean;
}

export function GetConnectionStatus(): Promise<ConnectionStatus>;
export function IsDeviceOwnerInstalled(): Promise<boolean>;
export function GetApps(): Promise<AppInfo[]>;
export function HideApp(arg1: string): Promise<void>;
export function ShowApp(arg1: string): Promise<void>;
export function InstallAPK(arg1: string): Promise<void>;
export function RunSetup(): Promise<void>;
